name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Check formatting
      run: make fmt-check
    - name: Build Rust
      run: make build
    - name: Clippy
      run: make clippy
    - name: Run tests
      run: make test